version: '3.8'

services:
  db:
    image: mariadb:10.6.9
    environment:
      - MYSQL_DATABASE=e-commerce_db
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_ROOT_PASSWORD=root_psw
    container_name: e-commerce_db
    ports:
      - '8989:3306'
    volumes:
      - './docker/shared/db/:/var/lib/mysql'

  php:
    build:
      context: .
      dockerfile: ./docker/images/php/Dockerfile
    environment:
      - PHP_IDE_CONFIG="serverName=docker"
    volumes:
      - './:/var/www'
      - 'var:/var/www/var/'
      - 'vendor:/var/www/vendor/'
      - 'bundles:/var/www/public/bundles/'
      - 'js:/var/www/public/js/'
    depends_on:
      - db

  nginx:
    image: nginx:alpine3.18
    volumes:
      - './docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/config/nginx/sites/:/etc/nginx/sites-available'
      - './docker/config/nginx/conf.d/:/etc/nginx/conf.d'
      - './:/var/www'
      - 'var:/var/www/var/'
      - 'vendor:/var/www/vendor/'
      - 'bundles:/var/www/public/bundles/'
      - 'js:/var/www/public/js/'
    ports:
      - '80:80'
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8081:80'
    depends_on:
      - db
    environment:
      - PMA_HOST=db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: e-commerce_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: e-commerce_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

volumes:
  bundles:
  js:
  vendor:
  var:
  es_data:
    driver: local
